/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SELECT = 1,
  anon_sym_FROM = 2,
  anon_sym_STAR = 3,
  anon_sym_COMMA = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COUNT = 7,
  anon_sym_WHERE = 8,
  anon_sym_LIMIT = 9,
  anon_sym_OFFSET = 10,
  anon_sym_OR = 11,
  anon_sym_AND = 12,
  anon_sym_NOT = 13,
  anon_sym_EQ = 14,
  anon_sym_BANG_EQ = 15,
  anon_sym_LT_GT = 16,
  anon_sym_GT = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_LT = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_NULL = 21,
  anon_sym_SQUOTE = 22,
  aux_sym_string_literal_token1 = 23,
  sym_number_literal = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym__identifier = 27,
  sym_source_file = 28,
  sym__statement = 29,
  sym_select_statement = 30,
  sym_select_list = 31,
  sym_column_list = 32,
  sym_select_expression = 33,
  sym_aggregate_function = 34,
  sym_column_name = 35,
  sym_file_name = 36,
  sym_where_clause = 37,
  sym_limit_clause = 38,
  sym_offset_clause = 39,
  sym_expression = 40,
  sym_or_expression = 41,
  sym_and_expression = 42,
  sym_not_expression = 43,
  sym_primary_expression = 44,
  sym_comparison_expression = 45,
  sym_literal = 46,
  sym_string_literal = 47,
  sym_boolean_literal = 48,
  aux_sym_column_list_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SELECT] = "SELECT",
  [anon_sym_FROM] = "FROM",
  [anon_sym_STAR] = "*",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COUNT] = "COUNT",
  [anon_sym_WHERE] = "WHERE",
  [anon_sym_LIMIT] = "LIMIT",
  [anon_sym_OFFSET] = "OFFSET",
  [anon_sym_OR] = "OR",
  [anon_sym_AND] = "AND",
  [anon_sym_NOT] = "NOT",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_NULL] = "NULL",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym__identifier] = "_identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_select_statement] = "select_statement",
  [sym_select_list] = "select_list",
  [sym_column_list] = "column_list",
  [sym_select_expression] = "select_expression",
  [sym_aggregate_function] = "aggregate_function",
  [sym_column_name] = "column_name",
  [sym_file_name] = "file_name",
  [sym_where_clause] = "where_clause",
  [sym_limit_clause] = "limit_clause",
  [sym_offset_clause] = "offset_clause",
  [sym_expression] = "expression",
  [sym_or_expression] = "or_expression",
  [sym_and_expression] = "and_expression",
  [sym_not_expression] = "not_expression",
  [sym_primary_expression] = "primary_expression",
  [sym_comparison_expression] = "comparison_expression",
  [sym_literal] = "literal",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_column_list_repeat1] = "column_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SELECT] = anon_sym_SELECT,
  [anon_sym_FROM] = anon_sym_FROM,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COUNT] = anon_sym_COUNT,
  [anon_sym_WHERE] = anon_sym_WHERE,
  [anon_sym_LIMIT] = anon_sym_LIMIT,
  [anon_sym_OFFSET] = anon_sym_OFFSET,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_NULL] = anon_sym_NULL,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym__identifier] = sym__identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_select_statement] = sym_select_statement,
  [sym_select_list] = sym_select_list,
  [sym_column_list] = sym_column_list,
  [sym_select_expression] = sym_select_expression,
  [sym_aggregate_function] = sym_aggregate_function,
  [sym_column_name] = sym_column_name,
  [sym_file_name] = sym_file_name,
  [sym_where_clause] = sym_where_clause,
  [sym_limit_clause] = sym_limit_clause,
  [sym_offset_clause] = sym_offset_clause,
  [sym_expression] = sym_expression,
  [sym_or_expression] = sym_or_expression,
  [sym_and_expression] = sym_and_expression,
  [sym_not_expression] = sym_not_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_comparison_expression] = sym_comparison_expression,
  [sym_literal] = sym_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_column_list_repeat1] = aux_sym_column_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SELECT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FROM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COUNT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WHERE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LIMIT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OFFSET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_select_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_select_list] = {
    .visible = true,
    .named = true,
  },
  [sym_column_list] = {
    .visible = true,
    .named = true,
  },
  [sym_select_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_aggregate_function] = {
    .visible = true,
    .named = true,
  },
  [sym_column_name] = {
    .visible = true,
    .named = true,
  },
  [sym_file_name] = {
    .visible = true,
    .named = true,
  },
  [sym_where_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_limit_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_offset_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_or_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_and_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_not_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_column_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(46);
      ADVANCE_MAP(
        '!', 5,
        '\'', 71,
        '(', 51,
        ')', 52,
        '*', 49,
        ',', 50,
        '-', 44,
        '<', 67,
        '=', 62,
        '>', 65,
        'A', 23,
        'C', 25,
        'F', 28,
        'L', 16,
        'N', 26,
        'O', 13,
        'S', 11,
        'W', 15,
        'f', 37,
        't', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == 'N') ADVANCE(83);
      if (lookahead == 'f') ADVANCE(89);
      if (lookahead == 't') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == 'N') ADVANCE(87);
      if (lookahead == 'f') ADVANCE(89);
      if (lookahead == 't') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '*') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead == 'C') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == 'C') ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == 'D') ADVANCE(59);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(55);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'F') ADVANCE(14);
      if (lookahead == 'R') ADVANCE(58);
      END_STATE();
    case 14:
      if (lookahead == 'F') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'H') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'I') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'I') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == 'L') ADVANCE(69);
      END_STATE();
    case 19:
      if (lookahead == 'L') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'L') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'M') ADVANCE(48);
      END_STATE();
    case 22:
      if (lookahead == 'M') ADVANCE(17);
      END_STATE();
    case 23:
      if (lookahead == 'N') ADVANCE(7);
      END_STATE();
    case 24:
      if (lookahead == 'N') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'O') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'O') ADVANCE(31);
      if (lookahead == 'U') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == 'R') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 'R') ADVANCE(9);
      END_STATE();
    case 30:
      if (lookahead == 'S') ADVANCE(12);
      END_STATE();
    case 31:
      if (lookahead == 'T') ADVANCE(60);
      END_STATE();
    case 32:
      if (lookahead == 'T') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(56);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(57);
      END_STATE();
    case 35:
      if (lookahead == 'T') ADVANCE(47);
      END_STATE();
    case 36:
      if (lookahead == 'U') ADVANCE(24);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SELECT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_FROM);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COUNT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COUNT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_WHERE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LIMIT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_OFFSET);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_NOT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(68);
      if (lookahead == '>') ADVANCE(64);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_NULL);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'L') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'L') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'N') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'O') ADVANCE(85);
      if (lookahead == 'U') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'O') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'T') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'T') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'U') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'U') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'a') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'e') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'l') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'r') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 's') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'u') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym__identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 72},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SELECT] = ACTIONS(1),
    [anon_sym_FROM] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COUNT] = ACTIONS(1),
    [anon_sym_WHERE] = ACTIONS(1),
    [anon_sym_LIMIT] = ACTIONS(1),
    [anon_sym_OFFSET] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(43),
    [sym__statement] = STATE(49),
    [sym_select_statement] = STATE(49),
    [anon_sym_SELECT] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_NOT,
    ACTIONS(9), 1,
      anon_sym_NULL,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      sym_number_literal,
    ACTIONS(17), 1,
      sym__identifier,
    STATE(12), 1,
      sym_primary_expression,
    STATE(20), 1,
      sym_not_expression,
    STATE(22), 1,
      sym_and_expression,
    STATE(26), 1,
      sym_or_expression,
    STATE(34), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 3,
      sym_column_name,
      sym_comparison_expression,
      sym_literal,
  [47] = 14,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_NOT,
    ACTIONS(9), 1,
      anon_sym_NULL,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      sym_number_literal,
    ACTIONS(17), 1,
      sym__identifier,
    STATE(12), 1,
      sym_primary_expression,
    STATE(20), 1,
      sym_not_expression,
    STATE(22), 1,
      sym_and_expression,
    STATE(26), 1,
      sym_or_expression,
    STATE(41), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 3,
      sym_column_name,
      sym_comparison_expression,
      sym_literal,
  [94] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_NOT,
    ACTIONS(9), 1,
      anon_sym_NULL,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      sym_number_literal,
    ACTIONS(17), 1,
      sym__identifier,
    STATE(12), 1,
      sym_primary_expression,
    STATE(20), 1,
      sym_not_expression,
    STATE(22), 1,
      sym_and_expression,
    STATE(27), 1,
      sym_or_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 3,
      sym_column_name,
      sym_comparison_expression,
      sym_literal,
  [138] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_NOT,
    ACTIONS(9), 1,
      anon_sym_NULL,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      sym_number_literal,
    ACTIONS(17), 1,
      sym__identifier,
    STATE(12), 1,
      sym_primary_expression,
    STATE(20), 1,
      sym_not_expression,
    STATE(23), 1,
      sym_and_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 3,
      sym_column_name,
      sym_comparison_expression,
      sym_literal,
  [179] = 2,
    ACTIONS(21), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(19), 13,
      ts_builtin_sym_end,
      anon_sym_FROM,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [199] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_NOT,
    ACTIONS(9), 1,
      anon_sym_NULL,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      sym_number_literal,
    ACTIONS(17), 1,
      sym__identifier,
    STATE(12), 1,
      sym_primary_expression,
    STATE(19), 1,
      sym_not_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 3,
      sym_column_name,
      sym_comparison_expression,
      sym_literal,
  [237] = 2,
    ACTIONS(25), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(23), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [256] = 2,
    ACTIONS(29), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(27), 11,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [274] = 2,
    ACTIONS(33), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(31), 11,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [292] = 2,
    ACTIONS(37), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(35), 11,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [310] = 3,
    ACTIONS(43), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 5,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(39), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
  [330] = 2,
    ACTIONS(47), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(45), 11,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [348] = 9,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_NULL,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      sym_number_literal,
    ACTIONS(17), 1,
      sym__identifier,
    STATE(15), 1,
      sym_primary_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 3,
      sym_column_name,
      sym_comparison_expression,
      sym_literal,
  [380] = 2,
    ACTIONS(51), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(49), 11,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [398] = 8,
    ACTIONS(17), 1,
      sym__identifier,
    ACTIONS(53), 1,
      anon_sym_STAR,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_COUNT,
    STATE(29), 1,
      sym_select_expression,
    STATE(47), 1,
      sym_column_list,
    STATE(55), 1,
      sym_select_list,
    STATE(38), 2,
      sym_aggregate_function,
      sym_column_name,
  [424] = 7,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_WHERE,
    ACTIONS(63), 1,
      anon_sym_LIMIT,
    ACTIONS(65), 1,
      anon_sym_OFFSET,
    STATE(21), 1,
      sym_where_clause,
    STATE(28), 1,
      sym_limit_clause,
    STATE(56), 1,
      sym_offset_clause,
  [446] = 5,
    ACTIONS(17), 1,
      sym__identifier,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_COUNT,
    STATE(39), 1,
      sym_select_expression,
    STATE(38), 2,
      sym_aggregate_function,
      sym_column_name,
  [463] = 1,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
      anon_sym_AND,
  [472] = 2,
    ACTIONS(71), 1,
      anon_sym_AND,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
  [483] = 5,
    ACTIONS(63), 1,
      anon_sym_LIMIT,
    ACTIONS(65), 1,
      anon_sym_OFFSET,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_limit_clause,
    STATE(46), 1,
      sym_offset_clause,
  [499] = 2,
    ACTIONS(77), 1,
      anon_sym_OR,
    ACTIONS(75), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
  [509] = 1,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
      anon_sym_OR,
  [517] = 4,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(81), 1,
      sym__identifier,
    STATE(17), 1,
      sym_file_name,
    STATE(25), 1,
      sym_string_literal,
  [530] = 1,
    ACTIONS(83), 4,
      ts_builtin_sym_end,
      anon_sym_WHERE,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
  [537] = 1,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
  [544] = 1,
    ACTIONS(87), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
  [551] = 3,
    ACTIONS(65), 1,
      anon_sym_OFFSET,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    STATE(46), 1,
      sym_offset_clause,
  [561] = 3,
    ACTIONS(89), 1,
      anon_sym_FROM,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_column_list_repeat1,
  [571] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_FROM,
    STATE(33), 1,
      aux_sym_column_list_repeat1,
  [581] = 3,
    ACTIONS(65), 1,
      anon_sym_OFFSET,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_offset_clause,
  [591] = 3,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      sym__identifier,
    STATE(42), 1,
      sym_column_name,
  [601] = 3,
    ACTIONS(101), 1,
      anon_sym_FROM,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_column_list_repeat1,
  [611] = 1,
    ACTIONS(106), 3,
      ts_builtin_sym_end,
      anon_sym_LIMIT,
      anon_sym_OFFSET,
  [617] = 1,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      anon_sym_OFFSET,
  [622] = 2,
    ACTIONS(99), 1,
      sym__identifier,
    STATE(50), 1,
      sym_column_name,
  [629] = 1,
    ACTIONS(110), 2,
      anon_sym_FROM,
      anon_sym_COMMA,
  [634] = 1,
    ACTIONS(112), 2,
      anon_sym_FROM,
      anon_sym_COMMA,
  [639] = 1,
    ACTIONS(101), 2,
      anon_sym_FROM,
      anon_sym_COMMA,
  [644] = 1,
    ACTIONS(114), 2,
      anon_sym_FROM,
      anon_sym_COMMA,
  [649] = 1,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
  [653] = 1,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
  [657] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [661] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [665] = 1,
    ACTIONS(124), 1,
      aux_sym_string_literal_token1,
  [669] = 1,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
  [673] = 1,
    ACTIONS(126), 1,
      anon_sym_FROM,
  [677] = 1,
    ACTIONS(128), 1,
      anon_sym_SQUOTE,
  [681] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [685] = 1,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
  [689] = 1,
    ACTIONS(134), 1,
      sym_number_literal,
  [693] = 1,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
  [697] = 1,
    ACTIONS(138), 1,
      sym_number_literal,
  [701] = 1,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
  [705] = 1,
    ACTIONS(142), 1,
      anon_sym_FROM,
  [709] = 1,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 179,
  [SMALL_STATE(7)] = 199,
  [SMALL_STATE(8)] = 237,
  [SMALL_STATE(9)] = 256,
  [SMALL_STATE(10)] = 274,
  [SMALL_STATE(11)] = 292,
  [SMALL_STATE(12)] = 310,
  [SMALL_STATE(13)] = 330,
  [SMALL_STATE(14)] = 348,
  [SMALL_STATE(15)] = 380,
  [SMALL_STATE(16)] = 398,
  [SMALL_STATE(17)] = 424,
  [SMALL_STATE(18)] = 446,
  [SMALL_STATE(19)] = 463,
  [SMALL_STATE(20)] = 472,
  [SMALL_STATE(21)] = 483,
  [SMALL_STATE(22)] = 499,
  [SMALL_STATE(23)] = 509,
  [SMALL_STATE(24)] = 517,
  [SMALL_STATE(25)] = 530,
  [SMALL_STATE(26)] = 537,
  [SMALL_STATE(27)] = 544,
  [SMALL_STATE(28)] = 551,
  [SMALL_STATE(29)] = 561,
  [SMALL_STATE(30)] = 571,
  [SMALL_STATE(31)] = 581,
  [SMALL_STATE(32)] = 591,
  [SMALL_STATE(33)] = 601,
  [SMALL_STATE(34)] = 611,
  [SMALL_STATE(35)] = 617,
  [SMALL_STATE(36)] = 622,
  [SMALL_STATE(37)] = 629,
  [SMALL_STATE(38)] = 634,
  [SMALL_STATE(39)] = 639,
  [SMALL_STATE(40)] = 644,
  [SMALL_STATE(41)] = 649,
  [SMALL_STATE(42)] = 653,
  [SMALL_STATE(43)] = 657,
  [SMALL_STATE(44)] = 661,
  [SMALL_STATE(45)] = 665,
  [SMALL_STATE(46)] = 669,
  [SMALL_STATE(47)] = 673,
  [SMALL_STATE(48)] = 677,
  [SMALL_STATE(49)] = 681,
  [SMALL_STATE(50)] = 685,
  [SMALL_STATE(51)] = 689,
  [SMALL_STATE(52)] = 693,
  [SMALL_STATE(53)] = 697,
  [SMALL_STATE(54)] = 701,
  [SMALL_STATE(55)] = 705,
  [SMALL_STATE(56)] = 709,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_name, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_name, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expression, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not_expression, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expression, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_expression, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_expression, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not_expression, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_expression, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 5, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_expression, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_expression, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_name, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_expression, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_list, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_list, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 6, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_column_list_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_column_list_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_where_clause, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_limit_clause, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_expression, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_expression, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aggregate_function, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [120] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_offset_clause, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_list, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 7, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sql(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
